### ISSUE TITLE
ipa-server-install: error: option --forwarder: invalid IP address 127.0.0.11

### ISSUE THREAD

**Issue by mmarzantowicz** [adelton/docker-freeipa#59]
I can not kick off FreeIPA container on docker within user defined network (docker 1.10). I get following error message during initialization of a new container:

```
$ cat var/log/ipa-server-configure-first.log 
Sat Mar 12 22:46:49 UTC 2016 /usr/sbin/init-data 
Sat Mar 12 22:46:50 UTC 2016 /usr/sbin/ipa-server-configure-first 
Usage: ipa-server-install [options]

ipa-server-install: error: option --forwarder: invalid IP address 127.0.0.11: cannot use loopback IP address
FreeIPA server configuration failed.
Sun Mar 13 10:49:50 UTC 2016 /usr/sbin/init-data 
Sun Mar 13 10:49:51 UTC 2016 /usr/sbin/ipa-server-configure-first 
Usage: ipa-server-install [options]

ipa-server-install: error: option --forwarder: invalid IP address 127.0.0.11: cannot use loopback IP address
FreeIPA server configuration failed.
Sun Mar 13 10:50:01 UTC 2016 /usr/sbin/init-data 
Sun Mar 13 10:50:01 UTC 2016 /usr/sbin/ipa-server-configure-first
```

I use docker-compose to manage my docker containers. This error happens when using version 2 of docker-compose configuration file which might be related to new networking (DNS) behavior introduced in docker. I'm using master-systemd branch of FreeIPA.

I tried to set `IPA_SERVER_INSTALL_OPTS='--forwarder=8.8.8.8'` or `IPA_SERVER_INSTALL_OPTS='--forwarder=127.0.0.1'` and also directly adding this lines to `ipa-server-install-options` file but neither seems to work (`ipa-server-install` just ignores them).

My system is Arch Linux:

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64
```

**Comment by adelton** [comment]
> Usage: ipa-server-install [options]
> ipa-server-install: error: option --forwarder: invalid IP address 127.0.0.11: cannot use loopback IP address

What do you try to achieve exactly? What the the forwarder address that you try to use?

**Comment by mmarzantowicz** [comment]
I'm trying to mitigate error message about inability to use loopback IP. I don't care about lookback because I'd like to have my own DNS inside docker container (one of reasons I install FreeIPA for). Currently docker changed its policy about `/etc/resolv.conf` and they put `127.0.0.11` there by default which doesn't seem to be accepted by `ipa-server-install`.

**Comment by mmarzantowicz** [comment]
I went with `127.0.0.1` (please note that it's not `127.0.0.11` used by docker!) because in `ipa-server-configure-first` (https://github.com/adelton/docker-freeipa/blob/master-systemd/ipa-server-configure-first#L191) there is a line that should set `FORWARDER=--no-forwarders` when one specifies `127.0.0.1`. But for me it doesn't work.

**Comment by adelton** [comment]
Could you try patch from https://github.com/adelton/docker-freeipa/commit/issue-59 ? It should allow you to put any `--forwarder` option to the `ipa-server-install-options` file and have it respected.

**Comment by mmarzantowicz** [comment]
It worked! I'm able to set arbitrary DNS forwarders and proceed with installation.

**Comment by adelton** [comment]
Thanks for verifying it. I've pushed the change to the master branch now.

**Comment by kevinpz** [comment]
Hi everyone,
I'm facing with the same issue, and I'm wondering if it's the same problem or not.
I'm trying to setup a Docker container for freeipa (docker-engine 1.10 and docker compose 1.7.0RC1). I'm on Centos7.
I git clone the master branch yesterday, and rebuild the image from source. (since I saw there are problems with the image on the docker hub)

The freeipa container will be my LDAP and DNS server reference. I'm in a isolated platform, without any other DNS. (it's for a POC)

So I'm trying to configure it, but it's always fail with the error message :
```
ipa-server-install: error: option --forwarder: invalid IP address 127.0.0.1: cannot use loopback IP address
```

Here my docker-compose file :
```
version: '2'

services:
  freeipa:
    image: freeipa
    container_name: freeipa
    hostname: ipa.dom.net
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/srv/ipa-data:/data'
    environment:
      - PASSWORD=Server123
      - IPA_SERVER_IP=172.16.1.10
      - IPA_SERVER_INSTALL_OPTS='--forwarder=127.0.0.1'
    ports:
      - '80:80'
      - '443:443'
      - '389:389'
      - '53:53/udp'
    networks:
      priv_network:
        ipv4_address: 172.16.1.10

networks:
  priv_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
```
I also try with the FORWARDER=127.0.0.1 env variable, but it's the same ...

I try to setup the same configuration in my personnal server connected to internet, and with a real forwarder (like 8.8.8.8), and it works great. 

So it is possible to configure the freeipa container to do not use any forwarder ? Or do I have a forwarder DNS working for the container first setup ?

Thanks a lot,
