### ISSUE TITLE
`$HOSTNAME` is not always set to FQDN

### ISSUE THREAD

**Issue by frol** [adelton/docker-freeipa#89]
This issue is related to the recent change: https://github.com/adelton/docker-freeipa/commit/9e6c20e962fa22dc71ce399f8327bd5ab7116cae

Docker Compose splits `hostname` into `hostname` and `domainname` using the first dot as a delimiter (hostname: `qq.example.com` -> hostname: `qq`, domainname: `example.com`).

```yaml
$ cat docker-compose.yml
version: '2'
services:
    qq:
      image: fedora
      hostname: "qq.example.com"
      entrypoint: /bin/sh
      command: ["-c", "env ; cat /etc/hosts ; uname -n"]
```

```
$ docker-compose up
qq_1  | HOSTNAME=qq
qq_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
qq_1  | PWD=/
qq_1  | SHLVL=1
qq_1  | HOME=/root
qq_1  | _=/usr/bin/env

qq_1  | 127.0.0.1       localhost
qq_1  | ::1     localhost ip6-localhost ip6-loopback
qq_1  | fe00::0 ip6-localnet
qq_1  | ff00::0 ip6-mcastprefix
qq_1  | ff02::1 ip6-allnodes
qq_1  | ff02::2 ip6-allrouters
qq_1  | 172.19.0.2      qq.example.com qq

qq_1  | qq.example.com
```

I suggest using `uname -n` instead of `$HOSTNAME` and `hostname -f`. At least, it works for me in both cases: `docker run` and `docker-compose up`.
